#!/usr/bin/env bash

set -e

export PATH=/home/ubuntu/.local/bin:$PATH

if [ $# -ne 3 ]; then
  echo "Usage: evaluate_agents <path_to_data_dir> <path_to_output_file> <num_episodes>"
  exit 1
fi

pushd "$(dirname "$0")" > /dev/null; pushd .. > /dev/null
  source venv/bin/activate
    touch "$2"
    mkdir -p "in-progress"
    mkdir -p "done"

    set +e
    set -x
    ls -d "$1"*/ | parallel --progress 'cp -r {} in-progress/; python3 ' \
      'agentevaluator.py --agent_data_directory=in-progress/{} --outfile="$2" --episodes="$3";' \
      'rm -rf in-progress/{}'
popd; popd
