#!/usr/bin/env bash

set -e

export PATH=/home/ubuntu/.local/bin:$PATH

pushd "$(dirname "$0")" > /dev/null; pushd .. > /dev/null
  # install dependencies
  virtualenv venv
  source venv/bin/activate
  pip3 install -r requirements.txt --user

  # make sure we have some configs
  if [ ! -d configs ]; then
    mkdir configs
    python3 generateconfigs.py
  fi

  NUM_PROCESSORS="$(grep -c ^processor /proc/cpuinfo)"

  set +e
  set -x
  ls -A configs | xargs -P "$NUM_PROCESSORS" -IN python3 agenttrainer.py --config_file N
popd; popd
