#!/usr/bin/env bash

set -e

export PATH=/home/ubuntu/.local/bin:$PATH

pushd "$(dirname "$0")" > /dev/null; pushd .. > /dev/null

  # make sure we have some configs
  if [ ! -d configs ]; then
    mkdir configs
    python3 generateconfigs.py
  fi

  NUM_PROCESSORS="$(grep -c ^processor /proc/cpuinfo)"
  #NUM_PROCESSORS=1

  set +e
  set -x
  ls -A configs | xargs -P "$NUM_PROCESSORS" -I% python3 \
    agenttrainer.py --config_file configs/%
popd; popd
