#!/usr/bin/env bash

set -x

pushd "$(dirname "$0")" > /dev/null; pushd .. > /dev/null
  # install dependencies
  pip3 install -r requirements.txt
  pip3 install tensorforce

  # make sure we have some configs
  if [ ! -d configs ]; then
    mkdir configs
    python3 generateconfigs.py
  fi

  NUM_PROCESSORS="$(grep -c ^processor /proc/cpuinfo)"

  ls -A configs | xargs -P "$NUM_PROCESSORS" -IN python3 agenttrainer.py --config_file N
popd; popd
